Models/Aircraft.cs
using System.Text.Json.Serialization;
// ReSharper disable UnusedAutoPropertyAccessor.Global

namespace Random_Realistic_Flight.Models;

public record Aircraft
{
    public string? Registration { get; set; }
    public string? ModeS { get; set; }
    public string? Model { get; set; }

}

Models/Departure.cs
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
// ReSharper disable ClassNeverInstantiated.Global
// ReSharper disable UnusedAutoPropertyAccessor.Global
// ReSharper disable CollectionNeverUpdated.Local
// ReSharper disable UnusedAutoPropertyAccessor.Local
// ReSharper disable MemberCanBePrivate.Global
// ReSharper disable CollectionNeverUpdated.Global

namespace Random_Realistic_Flight.Models;

public record Departure
{
    
    public Aircraft? Aircraft { get; set; }
    public string? Number { get; set; }
    [JsonPropertyName("departure")]
    public DepartureStats? DepartureStats { get; set; }
    public JsonObject? Arrival { get; set; }

    [JsonIgnore] public Airport? ArrivalAirport => Arrival?["airport"]?.Deserialize<Airport>(new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

    public record Airport
    {
        public string? Icao { get; set; }
        public string? Iata { get; set; }
        public string? Name { get; set; }
        
    }
}

Models/DepartureStats.cs
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
// ReSharper disable UnusedAutoPropertyAccessor.Global

namespace Random_Realistic_Flight.Models;

[SuppressMessage("ReSharper", "ClassNeverInstantiated.Global")]
public record DepartureStats
{
    public string? ScheduledTimeUtc { get; set; }
    public string? ActualTimeUtc { get; set; }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Random_Realistic_Flight.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Random_Realistic_Flight.Models;
using Random_Realistic_Flight.Services.Interfaces;
// ReSharper disable UnassignedGetOnlyAutoProperty
// ReSharper disable PropertyCanBeMadeInitOnly.Global
// ReSharper disable UnusedMember.Global

namespace Random_Realistic_Flight.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    private readonly IFlightService _flightService;
    private readonly IKeyService _keyService;
    private readonly string[] _timeSpans = { "12 Hours", "1 Day", "1 Week" };
    private readonly Random _random = new();

    [BindProperty] public string Airport { get; set; }
    public SelectList TimeSpansList { get; }
    [BindProperty] public string SelectedTimeSpanItem { get; set; }

    private TimeSpan SelectedTimeSpan
    {
        get
        {
            var timeSpanIdx = _timeSpans.ToList().IndexOf(SelectedTimeSpanItem);
            var selectedTimeSpan = timeSpanIdx switch
            {
                0 => TimeSpan.FromHours(12),
                1 => TimeSpan.FromDays(1),
                2 => TimeSpan.FromDays(7),
                _ => TimeSpan.FromDays(1)
            };
            return selectedTimeSpan;
        }
    }

    public SelectList AircraftList { get; set; } = new(Array.Empty<string>());
    [BindProperty] public string? SelectedAircraftItem { get; set; }
    public string OutputText { get; set; } = "";
    [BindProperty] public string Key { get; set; } = "";

    public IndexModel(ILogger<IndexModel> logger, IFlightService flightService, IKeyService keyService)
    {
        _logger = logger;
        _flightService = flightService;
        _keyService = keyService;
        TimeSpansList = new SelectList(_timeSpans);
        SelectedTimeSpanItem = _timeSpans[0];
        Airport = "";
    }

    public async Task<IActionResult> OnPostGetAircraft()
    {
        if (!string.IsNullOrWhiteSpace(Key))
        {
            _keyService.Key = Key;
        } else
        {
            OutputText = "Please enter a key.";
            return Page();
        }
        var aircraft = await _flightService.GetAircraftByAirportAsync(Airport, SelectedTimeSpan);
        AircraftList = new SelectList(aircraft);
        return Page();
    }

    public async Task<IActionResult> OnPostGetRandomFlight()
    {
        var flights = await _flightService.GetDeparturesAsync(Airport, SelectedTimeSpan);
        var flightsArray = flights as Departure[] ?? flights.ToArray();
        if (flightsArray.Length == 0)
        {
            OutputText = "No flights found";
            return Page();
        }

        flightsArray = flightsArray.Where(departure => !string.IsNullOrWhiteSpace(departure.Aircraft?.Model) && !string.IsNullOrWhiteSpace(SelectedAircraftItem) && SelectedAircraftItem.Contains(departure.Aircraft?.Model)).ToArray();
        if (flightsArray.Length == 0)
        {
            OutputText = "No flights found";
            return Page();
        }
        var randomIndex = _random.Next(0, flightsArray.Length);
        var randomFlight = flightsArray[randomIndex];
        OutputText = $"Flight {randomFlight.Number} to {randomFlight.ArrivalAirport?.Icao}\n" +
                     $"Departing at {randomFlight.DepartureStats.ScheduledTimeUtc}";
        return Page();
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Random_Realistic_Flight.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet() { }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Random Flight Generator</h1>
    
    
</div>
<body>
<div class="container">
    
    <form class="p-3" method="post">
        <div class="form-group p-2">
            <input type="text" class="form-control" asp-for="Key" placeholder="Enter your key here: "/>
        </div>
        <div class="form-group p-2">
            <label for="departure">Enter the departure airport here:</label>
            <input type="text" class="form-control" id="departure" placeholder="Enter departure airport." asp-for="Airport"/>
        </div>
        <div class="form-group p-2">
            <label for="timespan-select">How far back to look?</label>
            <select class="form-control" id="timespan-select" asp-items="Model.TimeSpansList" asp-for="SelectedTimeSpanItem"></select>
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="GetAircraft">Get Available Aircraft</button>
        <hr/>
        <div class="form-group p-2">
            <select class="form-control" asp-items="Model.AircraftList" asp-for="SelectedAircraftItem"></select>
        </div>
        <button type="submit" class="btn btn-primary" asp-page-handler="GetRandomFlight">Get Random Flight!</button>
    </form>
    <textarea asp-for="OutputText"></textarea>
</div>
</body>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Random Flight Generator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Random_Realistic_Flight.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">Random Flight Generator</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a> *@
                    @* </li> *@
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>